name: Spack Install Action
author: Kristian Zarebski (UKAEA)
description: Installs the Spack package management tool
inputs:
  version:
    description: version to install
    required: false
    default: latest
  packages:
    description: packages to install
    required: false
    default: ''

outputs:
  version:
    description: actual version installed
    value: ${{ steps.install-spack.outputs.version }}

runs:
  using: "composite"
  steps: 
    - name: Install Spack
      id: install-spack
      run: |
        SPACK_SRC_DIR=$GITHUB_WORKSPACE/.spack \
        SPACK_REF=${{ inputs.version }} \
        $GITHUB_ACTION_PATH/install-spack.sh echo $("${{ inputs.packages )}}" | xargs)
      shell: bash
  
branding:
  icon: terminal
  color: gray-dark