name: Spack Install Action
author: Kristian Zarebski (UKAEA)
description: Installs the Spack package management tool
inputs:
  version:
    description: version to install
    required: false
    default: latest
  packages:
    description: packages to install
    required: false
    default: ''
  environment_dir:
    description: path of virtual environment
    required: false
    default: none

runs:
  using: "composite"
  steps: 
    - name: Install Spack
      id: install-spack
      run: |
        SPACK_SRC_DIR=$GITHUB_WORKSPACE/.spack \
        SPACK_ENV_DIR=${{ inputs.environment_dir }} \
        SPACK_REF=${{ inputs.version }} \
        $GITHUB_ACTION_PATH/install-spack.sh ${{ inputs.packages }}
      shell: bash
  
branding:
  icon: terminal
  color: gray-dark