name: FAIR Data Pipeline Action Check
on: [release]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: kzscisoft/install-spack@testing
          with:
            packages: |
              hipscyl
              hipsparse
            environment_dir: my_spack_env